name: ci/cd

on:
  push:
    branches: ["main"]

permissions: write-all

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare unit tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r ./cast-service/requirements.txt

      - name: Run unit tests
        run: |
          pytest ./cast-service
          
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: pulling
      uses: actions/checkout@v3

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cast-service ./cast-service

    - name: docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: pushing
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cast-service:latest
