name: Microservices CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [cast-service, movie-service]

    services:
      postgres:
        image: postgres:12.1-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r ${{ matrix.service }}/requirements.txt

    - name: Run tests
      env:
        DATABASE_URI: postgresql://test_user:test_pass@localhost:5432/test_db
      run: |
        # Here, add your commands to run tests for each service
        pytest ${{ matrix.service }}/tests/

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t your-dockerhub-username/${{ matrix.service }}:${{ github.sha }} ${{ matrix.service }}
        docker push your-dockerhub-username/${{ matrix.service }}:${{ github.sha }}

    # Add additional deployment steps as needed
