name: Order Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        env:
          POSTGRES_USER: order_db_username
          POSTGRES_PASSWORD: order_db_password
          POSTGRES_DB: order_db_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install dependencies
        run: |
          pip install -r order-service/requirements.txt
  
      - name: Test with pytest
        run: |
          # Add commands to run tests for the movie service, e.g., pytest
          echo "Run tests for the order service"
  
      - name: Build and Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Log in to Docker Hub"
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Build Docker image"
          docker build -t your-dockerhub-username/order-service:${{ github.sha }} order-service/
          echo "Push Docker image to Docker Hub"
          docker push your-dockerhub-username/order-service:${{ github.sha }}
