name: Microservices CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [cast-service, movie-service]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r ${{ matrix.service }}/requirements.txt

    - name: Run tests
      run: |
        # Here, add your commands to run tests for each service
        echo "Run tests for ${{ matrix.service }}"
        # Example: pytest ${{ matrix.service }}/tests/

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t your-dockerhub-username/${{ matrix.service }}:${{ github.sha }} ${{ matrix.service }}
        docker push your-dockerhub-username/${{ matrix.service }}:${{ github.sha }}

    # Add additional deployment steps as needed
